(venv) (base) ashvintiwari@static-50-50-50-167 app-react %  uvicorn app:app --reload INFO:     Will watch for changes in these directories: ['/Users/ashvintiwari/Desktop/vivek/app-react'] INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit) INFO:     Started reloader process [80568] using StatReload INFO:     Started server process [80570] INFO:     Waiting for application startup.
up to date, audited 304 packages in 815ms

65 packages are looking for funding
  run shift-booking-app@0.0.0
├── https://opencollective.com/date-fns
│   └── date-fns@2.30.0
├── https://opencollective.com/typescript-eslint
│   └── @typescript-eslint/eslint-plugin@6.21.0, @typescript-eslint/scope-manager@6.21.0, @typescript-eslint/types@6.21.0, @typescript-eslint/type-utils@6.21.0, @typescript-eslint/typescript-estree@6.21.0, @typescript-eslint/utils@6.21.0, @typescript-eslint/visitor-keys@6.21.0, @typescript-eslint/parser@6.21.0
├── https://github.com/vitejs/vite?sponsor=1
│   └── vite@5.4.8
├─┬ https://paulmillr.com/funding/
│ │ └── chokidar@3.6.0
│ └── https://github.com/sponsors/jonschlinkert
│     └── picomatch@2.3.1
├─┬ https://opencollective.com/postcss/
│ │ └── postcss@8.4.47, postcss-js@4.0.1, postcss-load-config@4.0.2, postcss-nested@6.2.0
│ └── https://github.com/sponsors/ai
│     └── nanoid@3.3.7
├── https://github.com/sponsors/ljharb
│   └── resolve@1.22.8, is-core-module@2.15.1, function-bind@1.1.2, supports-preserve-symlinks-flag@1.0.0
├── https://github.com/sponsors/feross
│   └── run-parallel@1.2.0, queue-microtask@1.2.3
└─┬ https://opencollective.com/babel
  │ └── @babel/core@7.25.7
  └── https://opencollective.com/browserslist
      └── browserslist@4.24.0, caniuse-lite@1.0.30001667, update-browserslist-db@1.1.1 for details

5 vulnerabilities (4 moderate, 1 high)

To address all issues, run:
  npm audit fix

Run # npm audit report

@babel/helpers  <7.26.10
Severity: moderate
Babel has inefficient RexExp complexity in generated code with .replace when transpiling named capturing groups - https://github.com/advisories/GHSA-968p-4wvh-cqc8
fix available via `npm audit fix`
node_modules/@babel/helpers

cross-spawn  7.0.0 - 7.0.4
Severity: high
Regular Expression Denial of Service (ReDoS) in cross-spawn - https://github.com/advisories/GHSA-3xgq-45jj-v275
fix available via `npm audit fix`
node_modules/cross-spawn

esbuild  <=0.24.2
Severity: moderate
esbuild enables any website to send any requests to the development server and read the response - https://github.com/advisories/GHSA-67mh-4wv8-2f99
fix available via `npm audit fix`
node_modules/esbuild
  vite  0.11.0 - 6.1.5
  Depends on vulnerable versions of esbuild
  node_modules/vite

nanoid  <3.3.8
Severity: moderate
Predictable results in nanoid generation when given non-integer values - https://github.com/advisories/GHSA-mwcw-c2x4-8c55
fix available via `npm audit fix`
node_modules/nanoid

5 vulnerabilities (4 moderate, 1 high)

To address all issues, run:
  npm audit fix for details.
ERROR:    Traceback (most recent call last):
  File /Users/ashvintiwari/Documents/project/venv/lib/python3.12/site-packages/starlette/routing.py, line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File /Users/ashvintiwari/Documents/project/venv/lib/python3.12/site-packages/starlette/routing.py, line 610, in __aenter__
    await self._router.startup()
  File /Users/ashvintiwari/Documents/project/venv/lib/python3.12/site-packages/starlette/routing.py, line 711, in startup
    await handler()
  File /Users/ashvintiwari/Desktop/vivek/app-react/app.py, line 144, in startup_event
    build_frontend()
  File /Users/ashvintiwari/Desktop/vivek/app-react/app.py, line 55, in build_frontend
    subprocess.run([vite, --version], check=True, capture_output=True)
  File /opt/anaconda3/lib/python3.12/subprocess.py, line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File /opt/anaconda3/lib/python3.12/subprocess.py, line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File /opt/anaconda3/lib/python3.12/subprocess.py, line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'vite'

ERROR:    Application startup failed. Exiting.
WARNING:  StatReload detected changes in 'app.py'. Reloading...
INFO:     Started server process [80577]
INFO:     Waiting for application startup.

up to date, audited 304 packages in 847ms

65 packages are looking for funding
  run shift-booking-app@0.0.0
├── https://opencollective.com/date-fns
│   └── date-fns@2.30.0
├── https://opencollective.com/typescript-eslint
│   └── @typescript-eslint/eslint-plugin@6.21.0, @typescript-eslint/scope-manager@6.21.0, @typescript-eslint/types@6.21.0, @typescript-eslint/type-utils@6.21.0, @typescript-eslint/typescript-estree@6.21.0, @typescript-eslint/utils@6.21.0, @typescript-eslint/visitor-keys@6.21.0, @typescript-eslint/parser@6.21.0
├── https://github.com/vitejs/vite?sponsor=1
│   └── vite@5.4.8
├─┬ https://paulmillr.com/funding/
│ │ └── chokidar@3.6.0
│ └── https://github.com/sponsors/jonschlinkert
│     └── picomatch@2.3.1
├─┬ https://opencollective.com/postcss/
│ │ └── postcss@8.4.47, postcss-js@4.0.1, postcss-load-config@4.0.2, postcss-nested@6.2.0
│ └── https://github.com/sponsors/ai
│     └── nanoid@3.3.7
├── https://github.com/sponsors/ljharb
│   └── resolve@1.22.8, is-core-module@2.15.1, function-bind@1.1.2, supports-preserve-symlinks-flag@1.0.0
├── https://github.com/sponsors/feross
│   └── run-parallel@1.2.0, queue-microtask@1.2.3
└─┬ https://opencollective.com/babel
  │ └── @babel/core@7.25.7
  └── https://opencollective.com/browserslist
      └── browserslist@4.24.0, caniuse-lite@1.0.30001667, update-browserslist-db@1.1.1 for details

5 vulnerabilities (4 moderate, 1 high)

To address all issues, run:
  npm audit fix

Run # npm audit report

@babel/helpers  <7.26.10
Severity: moderate
Babel has inefficient RexExp complexity in generated code with .replace when transpiling named capturing groups - https://github.com/advisories/GHSA-968p-4wvh-cqc8
fix available via `npm audit fix`
node_modules/@babel/helpers

cross-spawn  7.0.0 - 7.0.4
Severity: high
Regular Expression Denial of Service (ReDoS) in cross-spawn - https://github.com/advisories/GHSA-3xgq-45jj-v275
fix available via `npm audit fix`
node_modules/cross-spawn

esbuild  <=0.24.2
Severity: moderate
esbuild enables any website to send any requests to the development server and read the response - https://github.com/advisories/GHSA-67mh-4wv8-2f99
fix available via `npm audit fix`
node_modules/esbuild
  vite  0.11.0 - 6.1.5
  Depends on vulnerable versions of esbuild
  node_modules/vite

nanoid  <3.3.8
Severity: moderate
Predictable results in nanoid generation when given non-integer values - https://github.com/advisories/GHSA-mwcw-c2x4-8c55
fix available via `npm audit fix`
node_modules/nanoid

5 vulnerabilities (4 moderate, 1 high)

To address all issues, run:
  npm audit fix for details.
ERROR:    Traceback (most recent call last):
  File /Users/ashvintiwari/Documents/project/venv/lib/python3.12/site-packages/starlette/routing.py, line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File /Users/ashvintiwari/Documents/project/venv/lib/python3.12/site-packages/starlette/routing.py, line 610, in __aenter__
    await self._router.startup()
  File /Users/ashvintiwari/Documents/project/venv/lib/python3.12/site-packages/starlette/routing.py, line 711, in startup
    await handler()
  File /Users/ashvintiwari/Desktop/vivek/app-react/app.py, line 144, in startup_event
    build_frontend()
  File /Users/ashvintiwari/Desktop/vivek/app-react/app.py, line 55, in build_frontend
    subprocess.run([vite, --version], check=True, capture_output=True)
  File /opt/anaconda3/lib/python3.12/subprocess.py, line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File /opt/anaconda3/lib/python3.12/subprocess.py, line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File /opt/anaconda3/lib/python3.12/subprocess.py, line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'vite'

ERROR:    Application startup failed. Exiting.